"""Added keys table

Revision ID: 289733547c1d
Revises: bd12576d7469
Create Date: 2026-04-25 18:25:31.699161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289733547c1d'
down_revision: Union[str, Sequence[str], None] = 'bd12576d7469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspector_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_value', sa.String(length=100), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspector_keys_id'), 'inspector_keys', ['id'], unique=False)
    op.create_index(op.f('ix_inspector_keys_key_value'), 'inspector_keys', ['key_value'], unique=True)
    op.add_column('users', sa.Column('fio', sa.String(length=255), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'fio')
    op.drop_index(op.f('ix_inspector_keys_key_value'), table_name='inspector_keys')
    op.drop_index(op.f('ix_inspector_keys_id'), table_name='inspector_keys')
    op.drop_table('inspector_keys')
    # ### end Alembic commands ###
