"""Add relations, dictionaries and Act models

Revision ID: 68538b0fb257
Revises: 3c345103c0c0
Create Date: 2026-04-25 16:28:25.902473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68538b0fb257'
down_revision: Union[str, Sequence[str], None] = '3c345103c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_reasons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_accident_reasons_id'), 'accident_reasons', ['id'], unique=False)
    op.create_table('accident_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_accident_types_id'), 'accident_types', ['id'], unique=False)
    op.create_table('bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bodies_id'), 'bodies', ['id'], unique=False)
    op.create_table('firms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    op.create_table('acts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('place', sa.String(length=500), nullable=False),
    sa.Column('victims', sa.Integer(), nullable=False),
    sa.Column('accident_type_id', sa.BigInteger(), nullable=False),
    sa.Column('accident_reason_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accident_reason_id'], ['accident_reasons.id'], ),
    sa.ForeignKeyConstraint(['accident_type_id'], ['accident_types.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acts_id'), 'acts', ['id'], unique=False)
    op.create_table('accident_participants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('act_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('car_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_participants_id'), 'accident_participants', ['id'], unique=False)
    op.create_foreign_key(None, 'cars', 'bodies', ['body_type_id'], ['id'])
    op.create_foreign_key(None, 'cars', 'firms', ['firm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_index(op.f('ix_accident_participants_id'), table_name='accident_participants')
    op.drop_table('accident_participants')
    op.drop_index(op.f('ix_acts_id'), table_name='acts')
    op.drop_table('acts')
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.drop_table('firms')
    op.drop_index(op.f('ix_bodies_id'), table_name='bodies')
    op.drop_table('bodies')
    op.drop_index(op.f('ix_accident_types_id'), table_name='accident_types')
    op.drop_table('accident_types')
    op.drop_index(op.f('ix_accident_reasons_id'), table_name='accident_reasons')
    op.drop_table('accident_reasons')
    # ### end Alembic commands ###
